const jsondb = {
  products: [
    {
      id: 1,
      name: "Candy Grabber",
      price: 29.99,
      description: "c'mon...Grab the candy!",
      category: "Toys",
      url: "candy-grabber",
      image: "/images/products/candyGrabber.jpg",
    },
    {
      id: 2,
      name: "Desktop Shield",
      price: 69.99,
      description:
        "for those who want to be protected from the evil rays of the sun!",
      category: "Office",
      url: "desktop-shield",
      image: "/images/products/desktop.png",
    },
    {
      id: 3,
      name: "Golden Cube",
      price: 9.99,
      description: "mmmmh...i like goooooold!",
      category: "Fidgets",
      url: "golden-cube",
      image: "/images/products/goldenCube.jpg",
    },
    {
      id: 4,
      name: "Golden Shnatz",
      price: 9.99,
      description: "It's a Harry Potter thing!",
      category: "Fidgets",
      url: "golden-shnatz",
      image: "/images/products/goldenShnatz.jpg",
    },
    {
      id: 5,
      name: "Chrome Hoptimist",
      price: 19.99,
      description: "Chrome Hoptimist, a classic Danish design icon",
      category: "Accessories",
      url: "hoptimist",
      image: "/images/products/hoptimistChrome.jpg",
    },
    {
      id: 6,
      name: "Hot Dog Maker",
      price: 100,
      description:
        "The Coca-Cola Hot Dog Maker is a fun way to cook and enjoy hot dogs.",
      category: "Kitchen",
      url: "hot-dog-maker",
      image: "/images/products/hotDogCocaCola.jpg",
    },
    {
      id: 7,
      name: "Robo",
      price: 9.99,
      description: "A nice little accessory for your desk!",
      category: "Accessories",
      url: "robot",
      image: "/images/products/robo.jpg",
    },
    {
      id: 8,
      name: "The Silver Grabber",
      price: 29.99,
      description: "The Classic Candy Grabber in a new, shiny silver look!",
      category: "Toys",
      url: "silver-grabber",
      image: "/images/products/silverGrabber.jpg",
    },
    {
      id: 9,
      name: "3d Puzzle",
      price: 49.99,
      description: "A 3d puzzle challenge!",
      category: "Toys",
      url: "3d-puzzle",
      image: "/images/products/3d-puzzle.jpg",
    },
  ],
};

export default jsondb;
